_wandb:
    value:
        cli_version: 0.23.1
        e:
            cn6hpdjb3bczjamtk59dpvd98eeqrk3k:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 48
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "51539607552"
                args:
                    - --policy-type
                    - mse
                codePath: hw1/src/hw1_imitation/train.py
                codePathLocal: src/hw1_imitation/train.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "114467717120"
                email: haley_dave@berkeley.edu
                executable: /Users/hdave/Desktop/2025-2026/CS285/homework_spring2026/hw1/.venv/bin/python3
                git:
                    commit: d9e044286d4d1b541e18e6d8e410265d52e28117
                    remote: https://github.com/berkeleydeeprlcourse/homework_spring2026.git
                host: wifi-10-44-93-116.wifi.berkeley.edu
                memory:
                    total: "51539607552"
                os: macOS-15.7.3-arm64-arm-64bit
                program: /Users/hdave/Desktop/2025-2026/CS285/homework_spring2026/hw1/src/hw1_imitation/train.py
                python: CPython 3.11.14
                root: /Users/hdave/Desktop/2025-2026/CS285/homework_spring2026/hw1
                startedAt: "2026-02-12T01:42:36.454120Z"
                writerId: cn6hpdjb3bczjamtk59dpvd98eeqrk3k
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 128
chunk_size:
    value: 8
data_dir:
    value: data
eval_interval:
    value: 10000
exp_name:
    value: null
flow_num_steps:
    value: 10
hidden_dims:
    value:
        - 256
        - 256
        - 256
log_interval:
    value: 100
lr:
    value: 0.0003
num_epochs:
    value: 400
num_video_episodes:
    value: 5
policy_type:
    value: mse
seed:
    value: 42
video_size:
    value:
        - 256
        - 256
wandb_project:
    value: hw1-imitation
weight_decay:
    value: 0
